In [1]:
#Practical no. : 05

In [3]:
#Aim : Creation Of Array (1D,2D and Multidimensional Array) using numpy

In [5]:
#Name : Santosh G. Kandalkar
#Roll no. : 74 (DS-B74)
#Section : B
#Subject : PE-I
#Date : 03/08/24

In [7]:
import numpy as np

In [9]:
arr1=np.array([10,20,30,40,50])

In [11]:
arr1

array([10, 20, 30, 40, 50])

In [13]:
arr2=np.array([[[10,20,30,40,50],[60,70,80,90,100]]])

In [15]:
arr2

array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]])

In [17]:
arr3=np.array([[10,20,30,40,50],[60,70,80,90,100],[15,25,35,45,55]])

In [19]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 15,  25,  35,  45,  55]])